apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rk05cp6y1-go 
  janus-idp.io/tekton: rk05cp6y1-go
  backstage.io/kubernetes-id: rk05cp6y1-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rk05cp6y1-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml